### ISSUE TITLE
"Give" 

### ISSUE THREAD

**Issue by Sumrrz** [RaySist1/qb-inventory#1]
Det er lige det inventory jeg har ledt efter i så lang tid, men man kan ikke give items. Er det noget du kan adde? :)

**Comment by RaySist1** [comment]
Jeg vil nok kigge på det og drop en release

**Comment by RaySist1** [comment]
Du kan downloade den nye version under releases
https://github.com/RaySist1/qb-inventory/releases/tag/qbcore, added Giveitem

**Comment by RaySist1** [comment]
Er der andet, så kan du altid kontakte mig på discord = 0x264

**Comment by Sumrrz** [comment]
Tusind tak bro!
Er joinet 200 discords, og der er et limit på 100? så kan ikke rigtige joine flere, ellers havde jeg 100p joinet! Kan være jeg lige joiner på min alt
